export const ADD_TO_CART ='ADD_TO_CART'
export const REMOVE_FROM_CART ='REMOVE_FROM_CART'
export const PRODUCT_LIST ='PRODUCT_LIST'


export const FETCH_PRODUCT_REQUESTED = 'FETCH_PRODUCT_REQUESTED';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';